------------------------------------------
-- Table USUARIO 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  USUARIO (
   ID  SERIAL NOT NULL,
   NOMBRE  VARCHAR(45) NOT NULL,
   APELLIDOS  VARCHAR(45) NOT NULL,
   EMAIL  VARCHAR(55) UNIQUE NOT NULL,
   CONTRASENIA  VARCHAR NOT NULL,
   FOTO  VARCHAR(75) NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID )
);



-- -----------------------------------------------------
-- Table  OFERTA_BUSCO_PENSION_APTO 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  OFERTA_BUSCO_PENSION_APTO  (
   ID  SERIAL NOT NULL,
   DINERO_DISPONIBLE  INT NOT NULL,
   NUMERO_CELULAR  BIGINT NOT NULL,
   TIPO_INMUEBLE  VARCHAR(20) NOT NULL,
   DESCRIPCION  VARCHAR(200) NOT NULL,
   USUARIO_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_OFERTA_BUSCO_PENSION_APTO_USUARIO 
    FOREIGN KEY ( USUARIO_ID )
    REFERENCES  USUARIO  ( ID )
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

-- -----------------------------------------------------
-- Table  UBICACION_BUSCO_PENSION_APTO 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  UBICACION_BUSCO_PENSION_APTO  (
   ID  SERIAL NOT NULL,
   PAIS  VARCHAR(25) NOT NULL,
   DEPARTAMENTO  VARCHAR(25) NOT NULL,
   CIUDAD  VARCHAR(25) NOT NULL,
   OFERTA_BUSCO_PENSION_APTO_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
    FOREIGN KEY ( OFERTA_BUSCO_PENSION_APTO_ID )
    REFERENCES  OFERTA_BUSCO_PENSION_APTO  ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table  CONVERSACION 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  CONVERSACION  (
   ID  SERIAL NOT NULL,
   ID_USUARIO_RECEPTOR  INT NOT NULL,
   USUARIO_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_CONVERSACION_USUARIO1 
    FOREIGN KEY ( USUARIO_ID )
    REFERENCES  USUARIO  ( ID )
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
 CONSTRAINT  fk_CONVERSACION_USUARIO_RECEPTOR1 
    FOREIGN KEY ( ID_USUARIO_RECEPTOR )
    REFERENCES  USUARIO  ( ID )
    ON DELETE NO ACTION
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table  MENSAJE 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  MENSAJE  (
   ID  SERIAL NOT NULL,
   MENSAJE  TEXT NULL,
   DIRECCION_MENSAJE VARCHAR(12) DEFAULT 'ENVIADO',
   CONVERSACION_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_MENSAJE_CONVERSACION1 
    FOREIGN KEY ( CONVERSACION_ID )
    REFERENCES  CONVERSACION  ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
);



-- -----------------------------------------------------
-- Table  CATEGORIA 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  CATEGORIA  (
   ID  SERIAL NOT NULL,
   NOMBRE  VARCHAR(45) UNIQUE NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID )
);


-- -----------------------------------------------------
-- Table  SUB_CATEGORIA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  SUB_CATEGORIA  (
   ID  SERIAL NOT NULL,
   NOMBRE  VARCHAR(45) UNIQUE NOT NULL,
   CATEGORIA_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_SUB_CATEGORIA_CATEGORIA1 
    FOREIGN KEY ( CATEGORIA_ID )
    REFERENCES  CATEGORIA  ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table  OFERTA_ARTICULO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  OFERTA_ARTICULO  (
   ID  SERIAL NOT NULL,
   DESCRIPCION  TEXT NOT NULL,
   PRECIO  INT NOT NULL,
   NUMERO_CELULAR  BIGINT NOT NULL,
   TITULO_AVISO  VARCHAR(70) NOT NULL,
   USUARIO_ID  INT NOT NULL,
   SUB_CATEGORIA_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_OFERTA_ARTICULO_USUARIO1 
    FOREIGN KEY ( USUARIO_ID )
    REFERENCES  USUARIO  ( ID )
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT  fk_OFERTA_ARTICULO_SUB_CATEGORIA1 
    FOREIGN KEY ( SUB_CATEGORIA_ID )
    REFERENCES  SUB_CATEGORIA  ( ID )
    ON DELETE NO ACTION
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table  UBICACION_OFERTA_ARTICULO 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  UBICACION_OFERTA_ARTICULO (
   ID  SERIAL NOT NULL,
   PAIS  VARCHAR(25) NOT NULL,
   DEPARTAMENTO  VARCHAR(25) NOT NULL,
   CIUDAD  VARCHAR(25) NOT NULL,
   OFERTA_ARTICULO_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
    FOREIGN KEY ( OFERTA_ARTICULO_ID )
    REFERENCES  OFERTA_ARTICULO ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table  OFERTA_PENSION 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  OFERTA_PENSION  (
   ID  SERIAL NOT NULL,
   HABITACIONES_DISPONIBLES  SMALLINT NOT NULL,
   HABITACIONES_INDIVIDUALES  SMALLINT NOT NULL,
   HABITACIONES_COMPARTIDAS  SMALLINT NOT NULL,
   NUM_HABITANTES  SMALLINT NOT NULL,
   HABITACIONES_BANIO_INTERNO  SMALLINT NOT NULL,
   GENERO_ADMITIDO  VARCHAR(15) NOT NULL,
   ALIMENTACION_INCLUIDA  BOOLEAN NOT NULL,
   PRECIO_MENSUAL  INT NOT NULL,
   NUM_CELULAR  BIGINT NOT NULL,
   TITULO_AVISO  VARCHAR(70) NOT NULL,
   DESCRIPCION_AVISO  TEXT NOT NULL,
   USUARIO_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_OFERTA_PENSION_USUARIO1 
    FOREIGN KEY ( USUARIO_ID )
    REFERENCES  USUARIO  ( ID )
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);



-- -----------------------------------------------------
-- Table  OFERTA_CASA_APTO 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  OFERTA_CASA_APTO  (
   ID  SERIAL NOT NULL,
   TIPO_INMUEBLE  VARCHAR(15) NOT NULL,
   NUM_HABITACIONES  SMALLINT NOT NULL,
   NUM_BANIOS  SMALLINT NOT NULL,
   AREA_INMUEBLE  SMALLINT NOT NULL,
   ESTANCIA_MINIMA  SMALLINT NOT NULL,
   SERVICIOS_PRINCIPALES  BOOLEAN NOT NULL,
   AMOBLADA  BOOLEAN NOT NULL,
   PRECIO_MENSUAL  INT NOT NULL,
   NUMERO_CELULAR  BIGINT NOT NULL,
   DESCRIPCION TEXT NOT NULL,
   TITULO_AVISO  VARCHAR(70) NOT NULL,
   USUARIO_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_OFERTA_CASA_APTO_USUARIO1 
    FOREIGN KEY ( USUARIO_ID )
    REFERENCES  USUARIO ( ID )
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table  OFERTA_HABITACION 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  OFERTA_HABITACION  (
   ID  SERIAL NOT NULL,
   AMOBLADA  BOOLEAN NOT NULL,
   TIPO_HABITACION  VARCHAR(15) NOT NULL,
   BANIO_INTERNO  BOOLEAN NOT NULL,
   GENERO_ADMITIDO  VARCHAR(15) NOT NULL,
   ALIMENTACION_INCLUIDA  BOOLEAN NOT NULL,
   AREA_INMUEBLE  SMALLINT NOT NULL,
   ESTANCIA_MINIMA  SMALLINT NOT NULL,
   NUM_HABITANTES  SMALLINT NOT NULL,
   NUMERO_CELULAR  BIGINT NOT NULL,
   PRECIO_MENSUAL  INT NOT NULL,
   TITULO_AVISO  VARCHAR(70) NOT NULL,
   DESCRIPCION  TEXT NOT NULL,
   USUARIO_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_OFERTA_HABITACION_USUARIO1 
    FOREIGN KEY ( USUARIO_ID )
    REFERENCES  USUARIO  ( ID )
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table  UBICACION_OFERTA_PENSION 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  UBICACION_OFERTA_PENSION (
   ID  SERIAL NOT NULL,
   PAIS  VARCHAR(25) NOT NULL,
   DEPARTAMENTO  VARCHAR(25) NOT NULL,
   CIUDAD  VARCHAR(25) NOT NULL,
   DIRECCION  VARCHAR(70) NOT NULL,
   CODIGO_POSTAL  INT NOT NULL,
   OFERTA_PENSION_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
    FOREIGN KEY ( OFERTA_PENSION_ID )
    REFERENCES  OFERTA_PENSION  ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table  UBICACION_OFERTA_CASA_APTO 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  UBICACION_OFERTA_CASA_APTO (
   ID  SERIAL NOT NULL,
   PAIS  VARCHAR(25) NOT NULL,
   DEPARTAMENTO  VARCHAR(25) NOT NULL,
   CIUDAD  VARCHAR(25) NOT NULL,
   DIRECCION  VARCHAR(70) NOT NULL,
   CODIGO_POSTAL  INT NOT NULL,
   OFERTA_CASA_APTO_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
    FOREIGN KEY ( OFERTA_CASA_APTO_ID )
    REFERENCES  OFERTA_CASA_APTO  ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table  UBICACION_OFERTA_HABITACION
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  UBICACION_OFERTA_HABITACION (
   ID  SERIAL NOT NULL,
   PAIS  VARCHAR(25) NOT NULL,
   DEPARTAMENTO  VARCHAR(25) NOT NULL,
   CIUDAD  VARCHAR(25) NOT NULL,
   DIRECCION  VARCHAR(70) NOT NULL,
   CODIGO_POSTAL  INT NOT NULL,
   OFERTA_HABITACION_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
    FOREIGN KEY ( OFERTA_HABITACION_ID )
    REFERENCES  OFERTA_HABITACION  ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
);




-- -----------------------------------------------------
-- Table  FOTO_ARTICULO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  FOTO_ARTICULO  (
   ID  SERIAL NOT NULL,
   FOTO  VARCHAR(45) NOT NULL,
   OFERTA_ARTICULO_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_FOTO_ARTICULO_OFERTA_ARTICULO1 
    FOREIGN KEY ( OFERTA_ARTICULO_ID )
    REFERENCES  OFERTA_ARTICULO  ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table  SERVICIO_ESPECIFICO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  SERVICIO_ESPECIFICO  (
   ID  SERIAL NOT NULL,
   SERVICIO  VARCHAR(20) UNIQUE NOT NULL,
   ICONO  VARCHAR(45) NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID )
);


-- -----------------------------------------------------
-- Table  NORMA_CASA 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  NORMA_CASA  (
   ID  SERIAL NOT NULL,
   NORMA  VARCHAR(30) UNIQUE NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID )
);


---------------------------------------------
-- VAMOS POR AQUI CON LA VERIFICACION #2-----
---------------------------------------------


-- -----------------------------------------------------
-- Table  FOTO_PENSION 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  FOTO_PENSION  (
   ID  SERIAL NOT NULL,
   FOTO  VARCHAR(45) NOT NULL,
   OFERTA_PENSION_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_FOTO_PENSION_OFERTA_PENSION1 
    FOREIGN KEY ( OFERTA_PENSION_ID )
    REFERENCES  OFERTA_PENSION  ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table  FOTO_CASA_APTO 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  FOTO_CASA_APTO  (
   ID  SERIAL NOT NULL,
   FOTO  VARCHAR(45) NOT NULL,
   OFERTA_CASA_APTO_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_FOTO_CASA_APTO_OFERTA_CASA_APTO1 
    FOREIGN KEY ( OFERTA_CASA_APTO_ID )
    REFERENCES  OFERTA_CASA_APTO  ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table  FOTO_HABITACION
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  FOTO_HABITACION  (
   ID  SERIAL NOT NULL,
   FOTO  VARCHAR(45) NOT NULL,
   OFERTA_HABITACION_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_FOTO_HABITACION_OFERTA_HABITACION1 
    FOREIGN KEY ( OFERTA_HABITACION_ID )
    REFERENCES  OFERTA_HABITACION ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
);




-- -----------------------------------------------------
-- Table  NORMA_CASA_has_OFERTA_HABITACION 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  NORMA_CASA_has_OFERTA_HABITACION  (
   ID  SERIAL NOT NULL,
   NORMA_CASA_ID  INT NOT NULL,
   OFERTA_HABITACION_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_NORMA_CASA_has_OFERTA_HABITACION_NORMA_CASA1 
    FOREIGN KEY ( NORMA_CASA_ID )
    REFERENCES  NORMA_CASA  ( ID )
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT  fk_NORMA_CASA_has_OFERTA_HABITACION_OFERTA_HABITACION1 
    FOREIGN KEY ( OFERTA_HABITACION_ID )
    REFERENCES  OFERTA_HABITACION ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
);



-- -----------------------------------------------------
-- Table  NORMA_CASA_has_OFERTA_CASA_APTO 
-- -----------------------------------------------------
/*
CREATE TABLE IF NOT EXISTS  NORMA_CASA_has_OFERTA_CASA_APTO  (
   ID  SERIAL NOT NULL,
   NORMA_CASA_ID  INT NOT NULL,
   OFERTA_CASA_APTO_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_NORMA_CASA_has_OFERTA_CASA_APTO_NORMA_CASA1 
    FOREIGN KEY ( NORMA_CASA_ID )
    REFERENCES  NORMA_CASA  ( ID )
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT  fk_NORMA_CASA_has_OFERTA_CASA_APTO_OFERTA_CASA_APTO1 
    FOREIGN KEY ( OFERTA_CASA_APTO_ID )
    REFERENCES  OFERTA_CASA_APTO  ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
*/


-- -----------------------------------------------------
-- Table  NORMA_CASA_has_OFERTA_PENSION 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  NORMA_CASA_has_OFERTA_PENSION (
   ID  SERIAL NOT NULL,
   NORMA_CASA_ID  INT NOT NULL,
   OFERTA_PENSION_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_NORMA_CASA_has_OFERTA_PENSION_NORMA_CASA1 
    FOREIGN KEY ( NORMA_CASA_ID )
    REFERENCES  NORMA_CASA  ( ID )
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT  fk_NORMA_CASA_has_OFERTA_PENSION_OFERTA_PENSION1 
    FOREIGN KEY ( OFERTA_PENSION_ID )
    REFERENCES  OFERTA_PENSION ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
);



-- -----------------------------------------------------
-- Table  SERVICIO_ESPECIFICO_has_OFERTA_PENSION 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  SERVICIO_ESPECIFICO_has_OFERTA_PENSION  (
   ID  SERIAL NOT NULL,
   SERVICIO_ESPECIFICO_ID  INT NOT NULL,
   OFERTA_PENSION_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_SERVICIO_ESPECIFICO_has_OFERTA_PENSION_SERVICIO_ESPE1 
    FOREIGN KEY ( SERVICIO_ESPECIFICO_ID )
    REFERENCES  SERVICIO_ESPECIFICO  ( ID )
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT  fk_SERVICIO_ESPECIFICO_has_OFERTA_PENSION_OFERTA_PENSIO1 
    FOREIGN KEY ( OFERTA_PENSION_ID )
    REFERENCES  OFERTA_PENSION  ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table  SERVICIO_ESPECIFICO_has_OFERTA_HABITACION 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  SERVICIO_ESPECIFICO_has_OFERTA_HABITACION  (
   ID  SERIAL NOT NULL,
   SERVICIO_ESPECIFICO_ID  INT NOT NULL,
   OFERTA_HABITACION_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_SERVICIO_ESPECIFICO_has_OFERTA_HABITACION_SERVICIO_E1 
    FOREIGN KEY ( SERVICIO_ESPECIFICO_ID )
    REFERENCES  SERVICIO_ESPECIFICO  ( ID )
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT  fk_SERVICIO_ESPECIFICO_has_OFERTA_HABITACION_OFERTA_HAB1 
    FOREIGN KEY ( OFERTA_HABITACION_ID )
    REFERENCES  OFERTA_HABITACION ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table  SERVICIO_ESPECIFICO_has_OFERTA_CASA_APTO 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  SERVICIO_ESPECIFICO_has_OFERTA_CASA_APTO  (
   ID  SERIAL NOT NULL,
   SERVICIO_ESPECIFICO_ID  INT NOT NULL,
   OFERTA_CASA_APTO_ID  INT NOT NULL,
   CREADO_EN TIMESTAMP DEFAULT NOW(),
   ACTUALIZADO_EN TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ( ID ),
  CONSTRAINT  fk_SERVICIO_ESPECIFICO_has_OFERTA_CASA_APTO_SERVICIO_ESPE1 
    FOREIGN KEY ( SERVICIO_ESPECIFICO_ID )
    REFERENCES  SERVICIO_ESPECIFICO  ( ID )
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT  fk_SERVICIO_ESPECIFICO_has_OFERTA_CASA_APTO_OFERTA_CASA_A1 
    FOREIGN KEY ( OFERTA_CASA_APTO_ID )
    REFERENCES  OFERTA_CASA_APTO  ( ID )
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

---------------------------------------------
-- VAMOS POR AQUI CON LA VERIFICACION #1-----
---------------------------------------------

